# Generated by Django 3.0.8 on 2020-07-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udaanapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
